allow_list_rules: []
block_list_patterns:
-   '@generated'
-   '@nolint'
block_list_rules: [UseTypesFromTypingRule, UseLintFixmeCommentRule]
packages:
-   fixit.rules
repo_root: .
rule_config: {}
use_noqa: false
